#!/usr/bin/env bash

set -e
echo "Starting docker build $APP_NAME $0"

cd docker
echo "Building containers"
docker-compose -f docker-compose.yml build
docker-compose stop
docker-compose -f docker-compose.yml run --rm app python manage.py migrate
docker-compose -f docker-compose.yml run --rm app python manage.py collectstatic --noinput
docker-compose -f docker-compose.yml up -d
echo ""
echo "Ready to start $APP_NAME"
docker-compose ps
